ask_on/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('forum.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^profile/(?P<idx>[0-9]+)/$', views.profile, name='profile'),
    url(r'^questions/(?P<pk>[0-9]+)/$', views.view_question, name='view_question'),
    url(r'^questions/(?P<abc>[0-9]+)/add_answer/$', views.add_answer, name='add_answer'),
    url(r'^questions/(?P<pk>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^questions/(?P<abc>[0-9]+)/favourite/$', views.favourite, name='favourite'),
    url(r'^feed/$', views.feed, name='feed'),
    url(r'^answers/(?P<pk>[0-9]+)/add_comment/$', views.add_comment, name='add_comment'),
    url(r'^thesaurus/$', views.thesaurus, name='thesaurus'),
    url(r'^wordoftheday/$', views.word_of_the_day, name='word_of_the_day'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    photo = models.FileField(blank=True)
    reputation = models.PositiveIntegerField(default=0)
    description = models.CharField(max_length=250, blank=True)
    domains = models.ManyToManyField("Domain", blank=True)

    def __str__(self):
        return self.user.username


class Question(models.Model):
    asked_by = models.ForeignKey(UserProfile, related_name="questions",
                                 null=True, blank=True, on_delete=models.SET_NULL)
    question = models.CharField(max_length=100)
    need = models.IntegerField(default=0)
    reports = models.PositiveIntegerField(default=0)
    domain = models.ForeignKey("Domain", related_name="domain_questions",
                               null=True, blank=True, on_delete=models.SET_NULL)
    time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.question


class Answer(models.Model):
    answered_by = models.ForeignKey(UserProfile, related_name="answers",
                                    null=True, blank=True, on_delete=models.SET_NULL)
    ques = models.ForeignKey(Question, related_name="question_ans", null=True, blank=True, on_delete=models.CASCADE)
    answer = models.CharField(max_length=500)
    reports = models.PositiveIntegerField(default=0)
    time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.answer


class AnswerComment(models.Model):
    comment_by = models.ForeignKey(UserProfile, related_name="comment_answer",
                                   null=True, blank=True, on_delete=models.SET_NULL)
    ans = models.ForeignKey(Answer, related_name="comments",
                            null=True, blank=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)
    upvotes = models.IntegerField(default=0)
    reports = models.PositiveIntegerField(default=0)
    time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.comment


class QuestionComment(models.Model):
    comment_by = models.ForeignKey(UserProfile, related_name="comment_question",
                                   null=True, blank=True, on_delete=models.SET_NULL)
    question = models.ForeignKey(Question, related_name="comments", on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)
    upvotes = models.IntegerField(default=0)
    reports = models.PositiveIntegerField(default=0)
    time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.comment


class Domain(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Favorite(models.Model):
    user = models.ForeignKey(UserProfile, related_name="favorites", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, related_name="question_favorites", on_delete=models.CASCADE)


class Vote(models.Model):
    user = models.ForeignKey(UserProfile, related_name="votes", on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, related_name="answer_votes", on_delete=models.CASCADE)

forum/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField(help_text=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('photo', 'description', 'domains')

forum/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from .forms import UserForm, UserProfileForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import UserProfile, Question, Answer, AnswerComment, Vote, Favorite, Domain
from django.http import HttpResponse
from django import forms
import random


def login(request):
    if request.user.is_authenticated:
            return render(request, 'forum/feed.html', {})
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    auth_login(request, user)
                    return render(request, 'forum/feed.html', {})
                else:
                    error = 'Your account is disabled.'
                    return render(request, 'forum/login.html', {'error': error})
            else:
                error = 'Incorrect Username or Password'
                return render(request, 'forum/login.html', {'error': error})
        else:
            return render(request, 'forum/login.html', {})


def logout(request):
    auth_logout(request)
    return redirect(reverse('forum:login'))


def register(request):
    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            auth_login(request, user)
            return redirect('forum:profile', idx=profile.id)
        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            error = "Error in registering"
            return render(request,
                          'forum/register.html',
                          {'user_form': user_form, 'profile_form': profile_form,
                           'error': error})

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                  'forum/register.html',
                  {'user_form': user_form, 'profile_form': profile_form})


@login_required(login_url='forum:login')
def profile(request, idx):
    client = get_object_or_404(UserProfile, pk=idx)

    return render(request, 'forum/user_profile.html', {'client': client})


@login_required(login_url='forum:login')
def add_question(request):
    if request.method == 'POST':
        word = request.POST.get('word', '')
        domain = request.POST.get('domain', '')
        domain2 = Domain.objects.get(name=domain)
        domain = Domain.objects.filter(name=domain)
        if domain:
            all_questions = Question()
            all_questions.question = word
            all_questions.domain = domain2
            all_questions.save()
            return render(request, 'forum/feed.html')
        else:
            error_message = 'No such Domain names exist!'
            return render(request, 'forum/add_question.html', {'error': error_message})

    if request.method == 'GET':
        return render(request, 'forum/add_question.html')


def search(request):
    if request.GET.get('search'):
        param = request.GET.get('search')
        questions = Question.objects.filter(question__icontains=param)
        if not questions.exists():
            return render(request, 'form/search.html', {'error': 'NO MATCHING QUESTIONS FOUND'})
        return render(request, 'forum/search.html', {'questions': questions})
    return render(request, 'forum/search.html', {})


def view_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'forum/view_question.html', {'question': question})


@login_required(login_url='forum:login')
def add_answer(request, abc):
    if request.method == 'POST':
        ans = request.POST.get('answer', '')
        ques = Question.objects.get(id=abc)
        # if ques:
        user = request.user
        profile = user.user_profile
        answer = Answer.objects.create(answered_by=profile, ques=ques, answer=ans)
        answer.save()
        return redirect('forum:view_question', pk=abc)
        # else:
        #     return redirect('forum:login')
    ques = get_object_or_404(Question, pk=abc)
    return render(request, 'forum/view_question.html', {'question': ques})


@login_required(login_url='forum:login')
def feed(request):
    ques = Question.objects.all()

    return render(request, 'forum/feed.html', {'ques': ques})


@login_required(login_url='forum:login')
def favourite(request, abc):
    if request.method == 'POST':
        ques = Question.objects.get(id=abc)
        # if ques:
        user = request.user
        profile = user.user_profile
        favourite = Favorite.objects.filter(user=profile, question=ques)
        if favourite.exists():
            return redirect('forum:view_question', pk=abc)
        favourite = Favorite.objects.create(user=profile, question=ques)
        favourite.save()
        return redirect('forum:view_question', pk=abc)
        # else:
        #     return redirect('forum:login')
    ques = get_object_or_404(Question, pk=abc)
    return render(request, 'forum/view_question.html', {'question': ques})


def add_comment(request, pk):
    if request.method == 'POST':
        answer = Answer.objects.get(id=pk)
        ques = answer.ques
        param = request.POST.get("comment", '')
        ans_comment = AnswerComment(comment_by=request.user.user_profile, ans=answer, comment=param)
        ans_comment.save()
        return redirect('forum:view_question', pk=ques.id)
    return render(request, 'forum/add_comment.html', {})


@login_required(login_url='forum:login')
def vote(request, pk):
    answer = Answer.objects.get(id=pk)
    ques = answer.ques
    if request.method == 'POST':
        if Vote.objects.filter(user=request.user.user_profile, answer=answer):
            return redirect('forum:view_question', pk=ques.id)
        v = Vote(user=request.user.user_profile, answer=answer)
        v.save()
        return redirect('forum:view_question', pk=ques.id)
    return redirect('forum:view_question', pk=ques.id)


@login_required(login_url='forum:login')
def thesaurus(request):
    words = request.user.user_profile.favorites.all()
    return render(request, 'forum/mythesaurus.html', {'words': words})


def word_of_the_day(request):
    words = Question.objects.all()
    word = random.choice(words)
    return render(request, 'forum/wordoftheday.html', {'word': word})

forum/templates/forum/add_comment.html
<form action="" method="post">
  {% csrf_token %}
  Comment <input type="text" name="comment"><br>
  <input type="submit" value="Submit Comment">
</form>

forum/templates/forum/add_question.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
        <title>Rango</title>
    </head>

    <body>

      <form method='POST'>
      {% csrf_token %}
      Word: <input type="text" name="word"><br>
      Domain: <input type="text" name="domain"><br>
      <input type="submit" name="Submit">
    </form>
    {% if error %}
      <p>{{ error }}</p>
    {% endif %}
    </body>
</html>

forum/templates/forum/feed.html
<h1>Ask ON</h1>


{% for q in ques %}
    <h3>Jargon : {{ q.question }}</h3>
    <h4>Domain : {{ q.domain }}</h4>
    <h6>Asked On : {{ q.time }}</h6>
    <br>
{% endfor %}

forum/templates/forum/login.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
        <title>Rango</title>
    </head>

    <body>

      <form method='POST'>
      {% csrf_token %}
      Username <input type="text" name="username"><br>
      Password <input type="password" name="password"><br>
      <input type="submit" name="Submit">
    </form>
    {% if error %}
      <p>{{ error }}</p>
    {% endif %}
    </body>
</html>

forum/templates/forum/mythesaurus.html
{% if words %}
  {% for word in words %}
    <h1>word.question</h1>
  {% endfor %}
{% else %}
  <h1> No favourites yet!! </h1>
{% endif %}

forum/templates/forum/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ask ON</title>
    </head>

    <body>
        <form id="user_form" method="post" action=""
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    </body>
</html>

forum/templates/forum/search.html
<form action="" method="get">
  Search <input type="text" name="search"><br>
  <input type="submit">
</form>

{% if questions %}
  {% for question in questions %}
    <h1>{{ question.question }}</h1>
  {% endfor %}
{% endif %}
{% if error %}
  <h1>NO MATCHES FOUND</h1>
{% endif %}

forum/templates/forum/user_profile.html
<h2>{{ client.reputation }}</h2>
<h2>{{ client.description }}</h2>
<h2>{{ client.domains }}</h2>
<h2>{{ client.words }}</h2>

<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.card {
 box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
 max-width: 300px;
 margin: auto;
 text-align: center;
 font-family: arial;
}

.title {
 color: grey;
 font-size: 18px;
}

button {
 border: none;
 outline: 0;
 display: inline-block;
 padding: 8px;
 color: white;
 background-color: #000;
 text-align: center;
 cursor: pointer;
 width: 100%;
 font-size: 18px;
}

a {
 text-decoration: none;
 font-size: 22px;
 color: black;
}

button:hover, a:hover {
 opacity: 0.7;
}
</style>
</head>
<body>

<h2 style="text-align:center">User Profile Card</h2>

<div class="card">
 <img src="{{ client.photo }}" alt="John" style="width:100%">
 <h1><h1>{{ client.user }}</h1></h1>
 <p class="title">CEO & Founder, Example</p>
 <p>{{ client.description }}</p>
 <div style="margin: 24px 0;">
</div>
<p><button>Contact</button></p>
</div>

</body>
</html>

forum/templates/forum/view_question.html
<h1>{{ question.question }}</h1>
<p>{{ question.id }}</p>
<form action="{% url 'forum:favourite' question.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Favourite"><br>
</form>


{% for answer in question.question_ans.all %}
  <p>{{ answer.answer }}</p>
  <p>{{ answer.answer_votes.count }}</p>
  <form action="{% url 'forum:vote' answer.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Vote"><br>
  </form>
  {% for comment in answer.comments.all %}
    <p>{{ comment.comment }}</p>
  {% endfor %}
  <a href="{% url 'forum:add_comment' answer.id %}">Add comment</a>
{% endfor %}
<h1>Add answer</h1>
<form action="{% url 'forum:add_answer' question.id %}" method="post">
  {% csrf_token %}
  Answer <input type="text" name="answer"><br>
  <input type="submit" value="Submit Answer"><br>
</form>

forum/templates/forum/wordoftheday.html
{{ word.question }}